### ISSUE TITLE
import 'dart-ext:unsafe_extension' fails to load on Mac OS X

### ISSUE THREAD

**Issue by mlesin** [mezoni/binary_interop#15]
To isolate problem from my code, I cloned this repo, run `pub get`, then `dart test/test.dart`.

Here is what I got in response:

    Cannot find extension library'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
    import 'dart-ext:unsafe_extension';
    ^

Running dart on Mac OS X 10.9.5

**Comment by mezoni** [comment]
Loading order of libraries (including native extension dynamic library):
1. dart-ext:unsafe_extension
2. unsafe_extension.dart

The reason is in that the Dart VM cannot load library via url `dart-ext:unsafe_extension`.
Unfortunately, Dart VM (error message) does not provide any additional information why this was happened (`library handler failed: import 'dart-ext:unsafe_extension'`).

The following steps can help determine the possible problem.

1 . Change dependency record in in `pubspec.yaml` to the following:
binary_interop: latest_version

2. Run `pub upgrade` and send to this issue the displayed messages in the terminal (console) of this command.

**Comment by mlesin** [comment]
I can't get what `binary_interop: latest_version` should do because I'm telling that I can't even run tests in your own repository, without a string of my own code:

    binary_interop mike$ git pull
    Already up-to-date.

    binary_interop mike$ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.

    nothing to commit, working directory clean

    binary_interop mike$ pub upgrade
    Resolving dependencies... (4.7s) 
      analyzer 0.25.0+1 (0.25.1-alpha.1 available)
      args 0.13.1
      barback 0.15.2+4
      binary_declarations 0.0.58
      binary_types 0.0.52
      build_tools 0.0.15
      ccompilers 0.2.10
      collection 1.1.1
      crypto 0.9.0
      file_utils 0.0.23
      glob 1.0.4
      globbing 0.1.20
      http_multi_server 1.3.2
      http_parser 0.0.2+6
      libc 0.0.10
      libffi6_extension 0.0.6
      libffi6_support 0.0.1
      libffi_binaries 0.6.7
      lists 0.0.21
      locking 0.0.9
      logging 0.11.1
      macro_processor 0.0.9
      matcher 0.12.0+1
      mime 0.9.3
      parser_error 0.0.1
      path 1.3.5
      patsubst 0.0.9
      pool 1.0.2
      pub_semver 1.2.1
      shelf 0.6.1+2
      shelf_static 0.2.2
      shelf_web_socket 0.0.1+2
      source_map_stack_trace 1.0.4
      source_maps 0.10.1
      source_span 1.1.2
      stack_trace 1.3.2
      string_scanner 0.1.3+1
      system_info 0.0.14
      test 0.12.3
      text 0.0.7
      unittest 0.12.3
      unsafe_extension 0.0.19
      watcher 0.9.5
      yaml 2.1.2
    No dependencies changed.

    binary_interop mike$ dart test/test.dart 
    Cannot find extension library'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
    import 'dart-ext:unsafe_extension';
    ^

**Comment by mezoni** [comment]
Very strange messages.
Please look at my messages:

Resolving dependencies... (7.6s) 
+ analyzer 0.25.0+1 (0.25.1-alpha.1 available)
> args 0.13.1 (was 0.13.0)
  barback 0.15.2+4
  binary_declarations 0.0.58
  binary_types 0.0.52
  build_tools 0.0.15
  ccompilers 0.2.10
> collection 1.1.1 (was 1.1.0)
+ crypto 0.9.0
  file_utils 0.0.23
+ glob 1.0.4
  globbing 0.1.20
+ http_multi_server 1.3.2
+ http_parser 0.0.2+6
  libc 0.0.10
> libffi6_extension 0.0.6 (was 0.0.5)
  libffi6_support 0.0.1
  libffi_binaries 0.6.7
  lists 0.0.21
> locking 0.0.9 (was 0.0.4)
> logging 0.11.1 (was 0.10.0)
  macro_processor 0.0.9
> matcher 0.12.0+1 (was 0.11.4+4)
+ mime 0.9.3
  parser_error 0.0.1
  path 1.3.5
  patsubst 0.0.9
> pool 1.0.2 (was 1.0.1)
> pub_semver 1.2.1 (was 1.1.0)
+ shelf 0.6.1+2
+ shelf_static 0.2.2
+ shelf_web_socket 0.0.1+2
+ source_map_stack_trace 1.0.4
+ source_maps 0.10.1
  source_span 1.1.2
> stack_trace 1.3.2 (was 1.3.1)
+ string_scanner 0.1.3+1
  system_info 0.0.14
+ test 0.12.3
  text 0.0.7
> unittest 0.12.3 (was 0.11.5+4)
  unsafe_extension 0.0.19
+ watcher 0.9.5
+ yaml 2.1.2
Downloading pub_semver 1.2.1...
Downloading unittest 0.12.3...
Downloading test 0.12.3...
Downloading pool 1.0.2...
Downloading source_map_stack_trace 1.0.4...
Downloading http_multi_server 1.3.2...
Downloading matcher 0.12.0+1...
Downloading source_maps 0.10.1...
Changed 25 dependencies!
Precompiling dependencies... 
Loading source assets... 
Loading libffi6_extension and unsafe_extension transformers... (1.8s) 
Setup libffi6_extension.so.
Already installed binary 'compiled/X86/linux/libffi6_extension.so'
The setup successful.
Setup libunsafe_extension.so.
Already installed binary 'compiled/X86/linux/libunsafe_extension.so'
The setup successful.
Precompiled libffi6_extension and unsafe_extension.
Precompiling executables... 
Loading source assets... 
Precompiled system_info:system_info.
Precompiled unittest:unittest.

```
Precompiling dependencies... 
Loading source assets... 
Loading libffi6_extension and unsafe_extension transformers... (1.8s) 
Setup libffi6_extension.so.
Already installed binary 'compiled/X86/linux/libffi6_extension.so'
The setup successful.
Setup libunsafe_extension.so.
Already installed binary 'compiled/X86/linux/libunsafe_extension.so'
The setup successful.
Precompiled libffi6_extension and unsafe_extension.
Precompiling executables... 
Loading source assets... 
Precompiled system_info:system_info.
Precompiled unittest:unittest.
```

```
Setup libunsafe_extension.so.
Already installed binary 'compiled/X86/linux/libunsafe_extension.so'
The setup successful.
Precompiled libffi6_extension and unsafe_extension.
```
Try delete in `pub-cache` all versions of the following packages:
- libffi6_extension
- unsafe_extension

This is a known limitation of Dart SDK and packaging system.

**Comment by mlesin** [comment]
Still the same effect:

    binary_interop mike$ rm -rf ~/.pub-cache/hosted/pub.dartlang.org/libffi*
    binary_interop mike$ rm -rf ~/.pub-cache/hosted/pub.dartlang.org/unsafe_extension-*

    binary_interop mike$ pub upgrade
    Resolving dependencies... (10.3s) 
      analyzer 0.25.0+1 (0.25.1-alpha.1 available)
      args 0.13.1
      barback 0.15.2+4
      binary_declarations 0.0.58
      binary_types 0.0.52
      build_tools 0.0.15
      ccompilers 0.2.10
      collection 1.1.1
      crypto 0.9.0
      file_utils 0.0.23
      glob 1.0.4
      globbing 0.1.20
      http_multi_server 1.3.2
      http_parser 0.0.2+6
      libc 0.0.10
      libffi6_extension 0.0.6
      libffi6_support 0.0.1
      libffi_binaries 0.6.7
      lists 0.0.21
      locking 0.0.9
      logging 0.11.1
      macro_processor 0.0.9
      matcher 0.12.0+1
      mime 0.9.3
      parser_error 0.0.1
      path 1.3.5
      patsubst 0.0.9
      pool 1.0.2
      pub_semver 1.2.1
      shelf 0.6.1+2
      shelf_static 0.2.2
      shelf_web_socket 0.0.1+2
      source_map_stack_trace 1.0.4
      source_maps 0.10.1
      source_span 1.1.2
      stack_trace 1.3.2
      string_scanner 0.1.3+1
      system_info 0.0.14
      test 0.12.3
      text 0.0.7
      unittest 0.12.3
      unsafe_extension 0.0.19
      watcher 0.9.5
      yaml 2.1.2
    Downloading libffi6_support 0.0.1...
    Downloading libffi6_extension 0.0.6...
    Downloading libffi_binaries 0.6.7...
    Downloading unsafe_extension 0.0.19...
    No dependencies changed.
    Precompiling dependencies... 
    Loading source assets... 
    Loading libffi6_extension and unsafe_extension transformers... 
    Setup libffi6_extension.dylib.
    Copying compiled binary 'compiled/X86_64/macos/libffi6_extension.dylib'
    The setup successful.
    Setup libunsafe_extension.dylib.
    Copying compiled binary 'compiled/X86_64/macos/libunsafe_extension.dylib'
    The setup successful.
    Precompiled libffi6_extension and unsafe_extension.

    binary_interop mike$ dart test/test.dart 
    Cannot find extension library'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
    import 'dart-ext:unsafe_extension';
    ^

**Comment by mezoni** [comment]
Problem only in that the Dart SDK and packaging system does not provide any way to perform `installation procedure`.
I am talking not about barback transformers (file per file, asset per asset).
I am talking about possibilty to take exclusive control when `pub` install packages.

There already exists for a long time an issue in Dart Bug Tracker but it seems that Dart Team does not have any interest to work in this direction.

As far as I know, Bob Nystrom (main developer of pub package manager) often love to say: "We have not time (to improve pub manager)".

So, I use some tricks to install (and distribute) ready-to-use multi-platform packages but sometimes installation procedure (performed by pub package manager) may not work as expected.
But at the same time, without some tricks, there is no possibilty to distribute multi-platform binary packages (with precompiled binaries or without them).

**Comment by mlesin** [comment]
By the way, just tried the following on debian jessie. With slight variation, result is the same. There is additional error message, maybe this would help?

    mike@l45:~/code/misc_projects/dart$ git clone https://github.com/mezoni/binary_interop.git
    Cloning into 'binary_interop'...
    remote: Counting objects: 540, done.
    remote: Total 540 (delta 0), reused 0 (delta 0), pack-reused 540
    Receiving objects: 100% (540/540), 96.41 KiB | 0 bytes/s, done.
    Resolving deltas: 100% (260/260), done.
    Checking connectivity... done.

    mike@l45:~/code/misc_projects/dart$ cd binary_interop/

    mike@l45:~/code/misc_projects/dart/binary_interop$ pub get
    Resolving dependencies... (7.8s) 
    + analyzer 0.25.0+1 (0.25.1-alpha.1 available)
    + args 0.13.1
    + barback 0.15.2+4
    + binary_declarations 0.0.58
    + binary_types 0.0.52
    + build_tools 0.0.15
    + ccompilers 0.2.10
    + collection 1.1.1
    + crypto 0.9.0
    + file_utils 0.0.23
    + glob 1.0.4
    + globbing 0.1.20
    + http_multi_server 1.3.2
    + http_parser 0.0.2+6
    + libc 0.0.10
    + libffi6_extension 0.0.6
    + libffi6_support 0.0.1
    + libffi_binaries 0.6.7
    + lists 0.0.21
    + locking 0.0.9
    + logging 0.11.1
    + macro_processor 0.0.9
    + matcher 0.12.0+1
    + mime 0.9.3
    + parser_error 0.0.1
    + path 1.3.5
    + patsubst 0.0.9
    + pool 1.0.2
    + pub_semver 1.2.1
    + shelf 0.6.1+2
    + shelf_static 0.2.2
    + shelf_web_socket 0.0.1+2
    + source_map_stack_trace 1.0.4
    + source_maps 0.10.1
    + source_span 1.1.2
    + stack_trace 1.3.2
    + string_scanner 0.1.3+1
    + system_info 0.0.14
    + test 0.12.3
    + text 0.0.7
    + unittest 0.12.3
    + unsafe_extension 0.0.19
    + watcher 0.9.5
    + yaml 2.1.2
    Downloading libffi6_support 0.0.1...
    Downloading libffi6_extension 0.0.6...
    Downloading libffi_binaries 0.6.7...
    Downloading libc 0.0.10...
    Downloading system_info 0.0.14...
    Downloading unsafe_extension 0.0.19...
    Downloading file_utils 0.0.23...
    Downloading binary_types 0.0.52...
    Downloading unittest 0.12.3...
    Downloading locking 0.0.9...
    Downloading build_tools 0.0.15...
    Downloading ccompilers 0.2.10...
    Downloading globbing 0.1.20...
    Downloading macro_processor 0.0.9...
    Downloading binary_declarations 0.0.58...
    Downloading test 0.12.3...
    Downloading patsubst 0.0.9...
    Downloading parser_error 0.0.1...
    Downloading text 0.0.7...
    Downloading lists 0.0.21...
    Changed 44 dependencies!
    Precompiling dependencies... 
    Loading source assets... 
    Loading libffi6_extension and unsafe_extension transformers... 
    Setup libffi6_extension.so.
    Copying compiled binary 'compiled/X86_64/linux/libffi6_extension.so'
    The setup successful.
    Setup libunsafe_extension.so.
    Copying compiled binary 'compiled/X86_64/linux/libunsafe_extension.so'
    The setup successful.
    Precompiled libffi6_extension and unsafe_extension.
    Precompiling executables... 
    Loading source assets... 
    Precompiled system_info:system_info.
    Precompiled unittest:unittest.

    mike@l45:~/code/misc_projects/dart/binary_interop$ dart test/test.dart 
    Unhandled exception:
    Bad state: extend() may only be called within a test.
    #0      expect (package:test/src/frontend/expect.dart:43:5)
    #1      main (file:///home/mike/code/misc_projects/dart/binary_interop/test/test.dart:19:3)
    #2      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:255)
    #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:142)

    mike@l45:~/code/misc_projects/dart/binary_interop$ pub run test/test.dart 
    Cannot load native extensions over http:'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
    import 'dart-ext:unsafe_extension';
    ^

**Comment by mezoni** [comment]
>> Still the same effect:

Precompiled binaries for Mac OS X was provided by [Kenneth Endfinger](https://github.com/kaendfinger).
I can only say again to him: "Great Thanks for the compilations of binary files".
But I was not able to compile them on Mac OS X, not test them.

But as far as know it tested and works in the following package on Mac OS X:
[osx](https://pub.dartlang.org/packages/osx).

This package uses [syscall](https://pub.dartlang.org/packages/syscall).

Syscall uses `binary_interop`.

The `binary interop` is a safest way because it does not dependent on any platform.
The `binary_interop` only rely on some small binary extension (which are platform depdendent).

Some advice.
Try to use `osx` package and contact an author [Kenneth Endfinger](https://github.com/kaendfinger) if it does not work.
And we all together will try to solve the problem.

P.S.
Problem only in that the Dart VM does not display message why it cannot load `native extension`.

**Comment by mezoni** [comment]
>> mike@l45:~/code/misc_projects/dart/binary_interop$ dart test/test.dart

Please try this.

1. Download `binary_interop`
2. Run `pub upgrade`
3. Run (inside) `binary_interop` it test
Eg.

Stop!!!
Problem in test package.

**Comment by mlesin** [comment]
That is exactly what I am doing all the time during the whole our conversation :)

**Comment by mezoni** [comment]
Also don't use `pub run test/test.dart`.
Because it can runs over `http` protocol.

**Comment by mezoni** [comment]
Over the `http protocol` Dart VM is not able locate the native extension.
Becuase `native extension` on `file` system but not on `http`.

**Comment by mezoni** [comment]
Please try again with new version 0.0.32.
And don't use `pub run` with any packages which works with the native extensions.
Use direct 'dart script.dart' instead.
This is bacause the `pub run` runs the Dart script over the `http` protocol (independently from the file system, shall we say, virtually in a sandbox).

**Comment by mezoni** [comment]
If the problem was solved then, please, tell me about result.
If you have some questions about `binary dart` then you can ask questions (in the other issue) and I will try to explain you about the correct usage.

**Comment by mlesin** [comment]
On linux, test is now passed when run directly. Have no access to macosx now, will check it later and tell you about result.
Thank you for your help!

**Comment by mezoni** [comment]
>> Thank you for your help!

Ask for help, do not hesitate.

**Comment by mlesin** [comment]
On macosx, nothing changed. Still the same error.

**Comment by mezoni** [comment]
>> On macosx, nothing changed. Still the same error.

Native extension is the same as the (low level) driver.
I don't know why Dart developers decides does not display information about the reason why Dart VM cannot load a native exension.

```
Cannot load native extensions over http:'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
import 'dart-ext:unsafe_extension';
^
```

As for me, this information is not enough.

Problem in that the I have possibilty to implement the multi-platform software but I don't have the possibilty to test the "driver" (a native extension) on every platform.
This is done by volunteers (other contributors).

Possible solution:
1. (Best) Ask for help (support) from Dart developers about the problem when it is not possible to know the reason of error message (library handler failed: import 'dart-ext:extension';).

2. (Good) Try contact an author (of compilation of Mac OS X native extension) [Kenneth Endfinger](https://github.com/kaendfinger). I do not want to transfer to it the problem, but he is a good programmer and I hope that he will be able to help.

I am sorry, but I know that it works on Mac OS X but I don't have Mac OS X installed on my machines.
Try at least package [osx](https://pub.dartlang.org/packages/osx) (it uses binary interop).

**Comment by mezoni** [comment]
>> On macosx, nothing changed. Still the same error.

Please send error message here (full list of lines).

**Comment by mezoni** [comment]
In the package `system_info` was fixed a bug on Mac OS X.
You can try again to use `binary_interop`.
Also you should to know that the support of Mac OS X 32-bit is not implemented.
More precisely, it has been discontinued as unclaimed environment.
There are no particular problems to implement it.

**Comment by mlesin** [comment]
Still doesn't work...

    mikebook:binary_interop mike$ pub upgrade
    Resolving dependencies... (6.7s) 
      analyzer 0.25.0+1 (0.25.1-alpha.2 available)
    > args 0.13.2 (was 0.13.1)
      barback 0.15.2+4
    > binary_declarations 0.0.59 (was 0.0.58)
    > binary_types 0.0.53 (was 0.0.52)
      build_tools 0.0.15
      ccompilers 0.2.10
      collection 1.1.1
      crypto 0.9.0
      file_utils 0.0.23
      glob 1.0.4
      globbing 0.1.20
      http_multi_server 1.3.2
    > http_parser 0.0.2+7 (was 0.0.2+6)
      libc 0.0.10
      libffi6_extension 0.0.6
      libffi6_support 0.0.1
      libffi_binaries 0.6.7
      lists 0.0.21
      locking 0.0.9
      logging 0.11.1
      macro_processor 0.0.9
      matcher 0.12.0+1
      mime 0.9.3
      parser_error 0.0.1
      path 1.3.5
      patsubst 0.0.9
      pool 1.0.2
      pub_semver 1.2.1
      shelf 0.6.1+2
      shelf_static 0.2.2
      shelf_web_socket 0.0.1+2
      source_map_stack_trace 1.0.4
      source_maps 0.10.1
      source_span 1.1.2
    > stack_trace 1.3.3 (was 1.3.2)
      string_scanner 0.1.3+1
    > system_info 0.0.15 (was 0.0.14)
    > test 0.12.3+2 (was 0.12.3)
      text 0.0.7
      unsafe_extension 0.0.19
    > watcher 0.9.6 (was 0.9.5)
    > yaml 2.1.3 (was 2.1.2)
    Downloading system_info 0.0.15...
    Downloading test 0.12.3+2...
    Downloading binary_types 0.0.53...
    Downloading binary_declarations 0.0.59...
    Changed 9 dependencies!
    Precompiling dependencies... 
    Loading source assets... 
    Loading libffi6_extension and unsafe_extension transformers... (1.3s) 
    Setup libffi6_extension.dylib.
    Already installed binary 'compiled/X86_64/macos/libffi6_extension.dylib'
    The setup successful.
    Setup libunsafe_extension.dylib.
    Already installed binary 'compiled/X86_64/macos/libunsafe_extension.dylib'
    The setup successful.
    Precompiled libffi6_extension and unsafe_extension.
    Precompiling executables... 
    Loading source assets... 
    Precompiled system_info:system_info.
    Precompiled test:test.

    mikebook:binary_interop mike$ dart test/test.dart 
    Cannot find extension library'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
    import 'dart-ext:unsafe_extension';
    ^

**Comment by mezoni** [comment]
Oh, yes.
For me this is very unhelpful error message.
Only message about that the `library handler failed` and no other additional information about the problem.

```
Cannot find extension library'package:unsafe_extension/src/unsafe_extension.dart': error: line 3 pos 1: library handler failed
import 'dart-ext:unsafe_extension';
^
```

Cany you run this script?

```dart
import "dart:io";
import "package:system_info/system_info.dart";

void main() {
  print("SysInfo.userSpaceBitness: ${SysInfo.userSpaceBitness}");
  print("Platform.version: ${Platform.version}");
}
```

**Comment by mezoni** [comment]
The fact that I'm not sure that `SysInfo.userSpaceBitness` works correctly on Mac OS X when executed on **Dart VM 32-bit **.
If you post here results of above script then I at least will be know that problem not in that the native extensions was installed incorrectly.

**Comment by mlesin** [comment]
Here is result:

    SysInfo.userSpaceBitness: 64
    Platform.version: 1.10.1 (Mon May 11 11:02:10 2015) on "macos_ia32"

**Comment by mezoni** [comment]
OK. Thanks.
This is the problem.
I will fix it soon.

**Comment by mezoni** [comment]
Fixed bug in `system_info`.
You can try again to use the `binary interop`.
But I think that without a 32-bit extensions it will not work.
But you can compile them and pull requests to adding them for the later usage.
After that everything should work.
Unfortunately I do not have on my machines Mac OS X (only different versions of Microsoft Windows and Linux Ubuntu).

**Comment by mlesin** [comment]
Now it works, thanks!

    $ dart test/test.dart 
    00:00 +0: Test binary interop
    Hello Dartisans 2015
    True is 1
    00:00 +1: All tests passed!

**Comment by mezoni** [comment]
Thank you, for your help.
